import { User } from './user.models';

export interface Repositorios {
    id: number,          // 222501812,
    node_id: string,          // MDEwOlJlcG9zaXRvcnkyMjI1MDE4MTI=,
    name: string,          // barber_app,
    full_name: string,          // MarcosVRSDev/barber_app,
    private: boolean,          // false,
    owner: User,          //  sddsadsadsa,
    html_url: string,          // https:,          ////github.com/MarcosVRSDev/barber_app,
    description: string,          // Primeiro aplicativo desenvolvido em Flutter. ,
    fork: boolean,          // false,
    url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app,
    forks_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/forks,
    keys_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/keys{/key_id},
    collaborators_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/collaborators{/collaborator},
    teams_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/teams,
    hooks_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/hooks,
    issue_events_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/issues/events{/number},
    events_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/events,
    assignees_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/assignees{/user},
    branches_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/branches{/branch},
    tags_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/tags,
    blobs_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/git/blobs{/sha},
    git_tags_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/git/tags{/sha},
    git_refs_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/git/refs{/sha},
    trees_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/git/trees{/sha},
    statuses_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/statuses/{sha},
    languages_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/languages,
    stargazers_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/stargazers,
    contributors_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/contributors,
    subscribers_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/subscribers,
    subscription_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/subscription,
    commits_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/commits{/sha},
    git_commits_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/git/commits{/sha},
    comments_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/comments{/number},
    issue_comment_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/issues/comments{/number},
    contents_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/contents/{+path},
    compare_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/compare/{base}...{head},
    merges_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/merges,
    archive_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/{archive_format}{/ref},
    downloads_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/downloads,
    issues_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/issues{/number},
    pulls_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/pulls{/number},
    milestones_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/milestones{/number},
    notifications_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/notifications{?since,all,participating},
    labels_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/labels{/name},
    releases_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/releases{/id},
    deployments_url: string,          // https:,          ////api.github.com/repos/MarcosVRSDev/barber_app/deployments,
    created_at: string,          // 2019-11-18T17:,          //09:,          //59Z,
    updated_at: string,          // 2019-12-01T19:,          //51:,          //29Z,
    pushed_at: string,          // 2019-12-01T19:,          //51:,          //27Z,
    git_url: string,          // git:,          ////github.com/MarcosVRSDev/barber_app.git,
    ssh_url: string,          // git@github.com:,          //MarcosVRSDev/barber_app.git,
    clone_url: string,          // https:,          ////github.com/MarcosVRSDev/barber_app.git,
    svn_url: string,          // https:,          ////github.com/MarcosVRSDev/barber_app,
    homepage: string,          // null,
    size: number,          // 3773,
    stargazers_count: number,          // 0,
    watchers_count: number,          // 0,
    language: string,          // Dart,
    has_issues: boolean,          // true,
    has_projects: boolean,          // true,
    has_downloads: boolean,          // true,
    has_wiki: boolean,          // true,
    has_pages: boolean,          // false,
    forks_count: number,          // 0,
    mirror_url: string,          // null,
    archived: boolean,          // false,
    disabled: boolean,          // false,
    open_issues_count: number,          // 1,
    license: string,          // null,
    forks: number,          // 0,
    open_issues: number,          // 1,
    watchers: number,          // 0,
    default_branch: string         // master
}